### ISSUE TITLE
ESP8266 resets to CWMODE=1 on every power cycle

### ISSUE THREAD

**Issue by trevorlazarus** [subpos/esp_firmware_v2#1]
Hi, I set CWMODE = 2 or 3 and when I power off and on the module, it defaults to CWMODE = 1, is this the intended behaviour?

**Comment by bleckers** [comment]
That is correct. This is set in user_init():

```
    //Promiscuous works only with station mode
    //wifi_send_pkt_freedom will error if not in station mode.
    //AT+CWMODE=1
    //AT+CWAUTOCONN=0

    if(at_wifiMode != STATION_MODE)
    {
    #ifdef DEBUG
        at_port_print("\r\nStation mode not set, setting station mode.\r\n");
    #endif

        ETS_UART_INTR_DISABLE();
        wifi_set_opmode(1);
        ETS_UART_INTR_ENABLE();
    }
```

It needs to be in station mode for the wifi_send_pkt_freedom function to work correctly.

**Comment by trevorlazarus** [comment]
Thanks @bleckers for the interesting project, wiring everything up today. will let you know how it goes.

**Comment by bleckers** [comment]
Good stuff :)

Just to note, I forgot to mention that all settings and changes you make will revert to default on reboot. I have updated the readme to reflect this and explained it a little more here - https://github.com/subpos/esp_firmware_v2/issues/2
